[versions]
agp = "8.12.2"
kotlin = "2.2.0"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.1"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
swiperefreshlayout = "1.1.0"
hilt = "2.56.2"
lifecycle = "2.9.1"
retrofit = "3.0.0"
okhttp = "4.12.0"
room = "2.7.2"
glide = "4.16.0"
navigation = "2.9.0"
biometric = "1.2.0-alpha05"
gson = "2.13.1"
coroutines = "1.10.2"
sdp = "1.1.1"
ssp = "1.1.1"
pinview = "1.4.4"
firebaseCrashlytics = "19.4.4"
googleGmsGoogleServices = "4.4.3"
googleFirebaseCrashlytics = "3.0.4"
firebaseMessaging = "24.1.2"
crypto = "6.5.1"
playServicesMaps = "19.2.0"
places = "4.3.1"
androidCore = "3.3.0"
zxingAndroidEmbedded = "4.3.0"
smartmaterialspinner = "2.0.0"
androidMapsUtils = "3.14.0"
playServicesLocation = "21.3.0"
ccp = "2.7.3"
libphonenumber = "9.0.8"
playServicesAuth = "21.3.0"
playServicesAuthApiPhone = "18.2.0"
playServicesVisionCommon = "19.1.3"
toasty = "1.5.2"
inappupdate = "2.1.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefreshlayout" }

# Hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }

# Lifecycle
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle" }

# Retrofit
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }

# OkHttp
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }

# Room
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

# Glide
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
glide-okhttp-integration = { group = "com.github.bumptech.glide", name = "okhttp3-integration", version.ref = "glide" }
glide-compiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "glide" }

# Navigation
navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }

# Biometric
biometric = { group = "androidx.biometric", name = "biometric", version.ref = "biometric" }

# Gson
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

# Coroutines
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }

# SDP and SSP
sdp-android = { group = "com.intuit.sdp", name = "sdp-android", version.ref = "sdp" }
ssp-android = { group = "com.intuit.ssp", name = "ssp-android", version.ref = "ssp" }

# Pinview
pinview = { group = "io.github.chaosleung", name = "pinview", version.ref = "pinview" }

# Firebase
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics", version.ref = "firebaseCrashlytics" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging", version.ref = "firebaseMessaging" }

# BCrypt
spring-security-crypto = { group = "org.springframework.security", name = "spring-security-crypto", version.ref = "crypto" }

# Google Maps
play-services-maps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "playServicesMaps" }
places = { group = "com.google.android.libraries.places", name = "places", version.ref = "places" }

# QR Code Scanner
android-core = { group = "com.google.zxing", name = "android-core", version.ref = "androidCore" }
zxing-android-embedded = { group = "com.journeyapps", name = "zxing-android-embedded", version.ref = "zxingAndroidEmbedded" }
smartmaterialspinner = { group = "com.github.chivorns", name = "smartmaterialspinner", version.ref = "smartmaterialspinner" }
android-maps-utils = { group = "com.google.maps.android", name = "android-maps-utils", version.ref = "androidMapsUtils" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "playServicesLocation" }
ccp = { group = "com.hbb20", name = "ccp", version.ref = "ccp" }
libphonenumber = { group = "com.googlecode.libphonenumber", name = "libphonenumber", version.ref = "libphonenumber" }
play-services-auth = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "playServicesAuth" }
play-services-auth-api-phone = { group = "com.google.android.gms", name = "play-services-auth-api-phone", version.ref = "playServicesAuthApiPhone" }
play-services-vision-common = { group = "com.google.android.gms", name = "play-services-vision-common", version.ref = "playServicesVisionCommon" }
toasty = { group = "com.github.GrenderG", name = "Toasty", version.ref = "toasty" }

# In App Update
inappupdate = { group = "com.google.android.play", name = "app-update", version.ref = "inappupdate" }
inappupdatektx = { group = "com.google.android.play", name = "app-update-ktx", version.ref = "inappupdate" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
navigation-safe-args = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }
google-firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "googleFirebaseCrashlytics" }

